[build-system]
requires = ["setuptools>=45", "setuptools_scm>=6.2"]
build-backend = "setuptools.build_meta"

[project]
name = "calculator-project"
version = "0.1.0"
description = "A simple calculator project"
readme = "README.md"
requires-python = ">=3.8"

[tool.setuptools]
packages = ["src"]