name: CICD-Demo
on:
  pull_request:
    branches:
    - main

jobs:
  cicd-demo:
    name: CICD RUN
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.9]
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .  # Install the project in editable mode
          pip install pytest pytest-cov flake8
          
      - name: Run Lint CODE
        run: |
          flake8 .

      - name: Run unit tests with pytest
        run: |
          pytest tests/ 
        
      
